/******************************************************************************
* templatinum [template]                                     wiki_template.hpp
*
* MediaWiki page generator from parsed code (C++).
*   Transforms a code_parse_result into a collection of MediaWiki-formatted
* pages organized as a full documentation hierarchy: module overview, class
* pages, namespace pages, enum pages, and a function index.
*
*   Default page layouts are built-in as MediaWiki markup strings rendered
* through tmpl_text_template. Each page kind has a named layout that can
* be overridden by the user at runtime, enabling full customization of the
* wiki output without modifying the template itself.
*
*   The output is a wiki_output containing a vector of named wiki_page
* values. Each page carries its title, content, kind, and categories.
* Downstream consumers (beams targeting a wiki API, file writers, etc.)
* can iterate the pages and route them independently.
*
* COMPONENTS:
*   - templatinum::wiki_page_kind - enum: module_overview, class_page, 
*       namespace_page, enum_page, function_index
*   - templatinum::wiki_page - a single generated wiki page
*   - templatinum::wiki_output - collection of wiki pages with lookup helpers
*   - templatinum::wiki_config - generation configuration
*   - templatinum::wiki_markup - static MediaWiki markup formatting helpers
*   - templatinum::tmpl_wiki_template - 
*       CRTP template: code_parse_result -> wiki_output
*
* FEATURE DEPENDENCIES:
*   D_ENV_CPP_FEATURE_LANG_RVALUE_REFERENCES   - move semantics
*   D_ENV_CPP_FEATURE_LANG_ALIAS_TEMPLATES     - using aliases
*   D_ENV_CPP_FEATURE_LANG_LAMBDAS             - lambda closures
*
* PORTABLE ACROSS:
*   C++11, C++14, C++17, C++20, C++23, C++26
*
* 
* path:      /inc/templatinum/template/markup/wiki/wiki_template.hpp
* author(s): Samuel 'teer' Neal-Blim                          date: 2026.03.26
******************************************************************************/

#ifndef TEMPLATINUM_WIKI_TEMPLATE_
#define TEMPLATINUM_WIKI_TEMPLATE_ 1

// require the C++ framework header
#ifndef DJINTERP_
    #error "wiki_template.hpp requires djinterp.h first"
#endif

#ifndef __cplusplus
    #error "wiki_template.hpp requires C++ compilation mode"
#endif

#if !D_ENV_LANG_IS_CPP11_OR_HIGHER
    #error "wiki_template.hpp requires C++11 or higher"
#endif

#include <cstddef>
#include <functional>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "template.hpp"
#include "code_template.hpp"
#include "text_template.hpp"


NS_DJINTERP
NS_TEMPLATINUM


///////////////////////////////////////////////////////////////////////////////
///             I.    PAGE CLASSIFICATION                                   ///
///////////////////////////////////////////////////////////////////////////////

// wiki_page_kind
//   enum: the type of wiki page generated.
enum class wiki_page_kind
{
    // top-level overview page listing all modules,
    // classes, and namespaces in the parsed source
    module_overview,

    // dedicated page for a class or struct
    class_page,

    // dedicated page for a namespace
    namespace_page,

    // dedicated page for an enum
    enum_page,

    // alphabetical index of all functions/methods
    function_index,

    // custom page generated by user-defined logic
    custom
};


///////////////////////////////////////////////////////////////////////////////
///             II.   WIKI PAGE                                             ///
///////////////////////////////////////////////////////////////////////////////

// wiki_page
//   struct: a single generated wiki page carrying its title,
// MediaWiki markup content, kind, and category tags.
struct wiki_page
{
    // page title (used as the wiki page name)
    std::string title;

    // full MediaWiki markup content
    std::string content;

    // the kind of page this is
    wiki_page_kind kind;

    // MediaWiki categories (e.g., "Classes", "API")
    std::vector<std::string> categories;

    // the source symbol's qualified name (empty for
    // overview/index pages)
    std::string source_symbol;

    wiki_page()
        : title()
        , content()
        , kind(wiki_page_kind::custom)
        , categories()
        , source_symbol()
    {
    };
};


///////////////////////////////////////////////////////////////////////////////
///             III.  WIKI OUTPUT                                           ///
///////////////////////////////////////////////////////////////////////////////

// wiki_output
//   struct: the aggregate output of a wiki generation pass.
// Contains all generated pages plus metadata.
struct wiki_output
{
    // all generated pages
    std::vector<wiki_page> pages;

    // source file that was parsed (for provenance)
    std::string source_file;

    // true if generation completed without errors
    bool success;

    wiki_output()
        : pages()
        , source_file()
        , success(false)
    {
    };

    // page_count
    //   method: returns the total number of generated pages.
    std::size_t page_count() const
    {
        return pages.size();
    };

    // find
    //   method: finds a page by title. Returns nullptr if
    // not found.
    const wiki_page* find(
        const std::string& _title) const
    {
        for (const auto& page : pages)
        {
            if (page.title == _title)
            {
                return &page;
            }
        }

        return nullptr;
    };

    // pages_of_kind
    //   method: returns all pages of a given kind.
    std::vector<const wiki_page*>
    pages_of_kind(wiki_page_kind _kind) const
    {
        std::vector<const wiki_page*> result;

        for (const auto& page : pages)
        {
            if (page.kind == _kind)
            {
                result.push_back(&page);
            }
        }

        return result;
    };
};


///////////////////////////////////////////////////////////////////////////////
///             IV.   CONFIGURATION                                         ///
///////////////////////////////////////////////////////////////////////////////

// wiki_config
//   struct: controls what pages are generated and how they
// are named and categorized.
struct wiki_config
{
    // prefix prepended to all page titles (e.g., "API/"
    // produces "API/MyClass")
    std::string title_prefix;

    // default category applied to all pages; additional
    // per-kind categories are added automatically
    std::string default_category;

    // ---- generation toggles ----

    // when true, generate the module overview page
    bool generate_overview;

    // when true, generate individual class/struct pages
    bool generate_class_pages;

    // when true, generate namespace pages
    bool generate_namespace_pages;

    // when true, generate enum pages
    bool generate_enum_pages;

    // when true, generate the function index page
    bool generate_function_index;

    // ---- content toggles ----

    // when true, include access specifiers (public,
    // private, protected) in member listings
    bool show_access;

    // when true, include source file and line number
    // references in symbol documentation
    bool show_source_location;

    // when true, include inheritance hierarchy on class
    // pages
    bool show_inheritance;

    // when true, include the list of #include
    // dependencies on overview and class pages
    bool show_dependencies;

    wiki_config()
        : title_prefix()
        , default_category("API")
        , generate_overview(true)
        , generate_class_pages(true)
        , generate_namespace_pages(true)
        , generate_enum_pages(true)
        , generate_function_index(true)
        , show_access(true)
        , show_source_location(true)
        , show_inheritance(true)
        , show_dependencies(true)
    {
    };
};


///////////////////////////////////////////////////////////////////////////////
///             V.    MEDIAWIKI MARKUP HELPERS                              ///
///////////////////////////////////////////////////////////////////////////////

// wiki_markup
//   struct: static helper methods for generating MediaWiki
// markup fragments. Used internally by the default layouts
// and available for custom layouts.
struct wiki_markup
{
    // heading
    //   function: wraps text in a MediaWiki heading.
    // _level 1 = "= text =", 2 = "== text ==", etc.
    static std::string heading(
        const std::string& _text,
        int _level = 2)
    {
        std::string eq(_level, '=');

        return eq + " " + _text + " " + eq + "\n";
    };

    // bold
    //   function: wraps text in bold markup.
    static std::string bold(const std::string& _text)
    {
        return "'''" + _text + "'''";
    };

    // italic
    //   function: wraps text in italic markup.
    static std::string italic(
        const std::string& _text)
    {
        return "''" + _text + "''";
    };

    // code_inline
    //   function: wraps text in inline code markup.
    static std::string code_inline(
        const std::string& _text)
    {
        return "<code>" + _text + "</code>";
    };

    // code_block
    //   function: wraps text in a syntax-highlighted code
    // block.
    static std::string code_block(
        const std::string& _text,
        const std::string& _lang = "cpp")
    {
        return "<syntaxhighlight lang=\"" + _lang
            + "\">\n" + _text
            + "\n</syntaxhighlight>\n";
    };

    // link
    //   function: creates an internal wiki link.
    // _target is the page name, _display is optional
    // display text.
    static std::string link(
        const std::string& _target,
        const std::string& _display = "")
    {
        if (_display.empty())
        {
            return "[[" + _target + "]]";
        }

        return "[[" + _target + "|" + _display + "]]";
    };

    // category
    //   function: creates a category tag.
    static std::string category(
        const std::string& _cat)
    {
        return "[[Category:" + _cat + "]]\n";
    };

    // table_start
    //   function: opens a MediaWiki table.
    static std::string table_start(
        const std::string& _class = "wikitable")
    {
        return "{| class=\"" + _class + "\"\n";
    };

    // table_header
    //   function: creates a table header row.
    static std::string table_header(
        const std::vector<std::string>& _cols)
    {
        std::string row = "|-\n";

        for (std::size_t i = 0; i < _cols.size(); ++i)
        {
            row += "! " + _cols[i] + "\n";
        }

        return row;
    };

    // table_row
    //   function: creates a table data row.
    static std::string table_row(
        const std::vector<std::string>& _cells)
    {
        std::string row = "|-\n";

        for (std::size_t i = 0;
             i < _cells.size();
             ++i)
        {
            row += "| " + _cells[i] + "\n";
        }

        return row;
    };

    // table_end
    //   function: closes a MediaWiki table.
    static std::string table_end()
    {
        return "|}\n";
    };

    // horizontal_rule
    //   function: inserts a horizontal rule.
    static std::string horizontal_rule()
    {
        return "----\n";
    };

    // bullet
    //   function: creates a bullet list item.
    static std::string bullet(
        const std::string& _text,
        int _depth = 1)
    {
        return std::string(_depth, '*') + " "
            + _text + "\n";
    };

    // symbol_kind_string
    //   function: returns a human-readable string for a
    // code_symbol_kind value.
    static const char*
    symbol_kind_string(code_symbol_kind _kind)
    {
        switch (_kind)
        {
            case code_symbol_kind::namespace_decl:
                return "Namespace";
            case code_symbol_kind::class_decl:
                return "Class";
            case code_symbol_kind::struct_decl:
                return "Struct";
            case code_symbol_kind::union_decl:
                return "Union";
            case code_symbol_kind::enum_decl:
                return "Enum";
            case code_symbol_kind::enum_constant:
                return "Enumerator";
            case code_symbol_kind::function_decl:
                return "Function";
            case code_symbol_kind::method_decl:
                return "Method";
            case code_symbol_kind::constructor:
                return "Constructor";
            case code_symbol_kind::destructor:
                return "Destructor";
            case code_symbol_kind::operator_decl:
                return "Operator";
            case code_symbol_kind::variable_decl:
                return "Variable";
            case code_symbol_kind::field_decl:
                return "Field";
            case code_symbol_kind::typedef_decl:
                return "Typedef";
            case code_symbol_kind::type_alias:
                return "Type Alias";
            case code_symbol_kind::template_decl:
                return "Template";
            case code_symbol_kind::macro_definition:
                return "Macro";
            case code_symbol_kind::concept_decl:
                return "Concept";
            case code_symbol_kind::using_decl:
                return "Using";
            default:
                return "Symbol";
        }
    };

    // access_string
    //   function: returns a MediaWiki-formatted access
    // specifier badge.
    static std::string
    access_string(code_access _access)
    {
        switch (_access)
        {
            case code_access::public_access:
                return "{{access|public}}";
            case code_access::protected_access:
                return "{{access|protected}}";
            case code_access::private_access:
                return "{{access|private}}";
            default:
                return "";
        }
    };
};


///////////////////////////////////////////////////////////////////////////////
///             VI.   DEFAULT LAYOUT KEYS                                   ///
///////////////////////////////////////////////////////////////////////////////

// layout key constants used to register and look up
// text_template overrides.

// D_WIKI_LAYOUT_OVERVIEW
//   constant: layout key for the module overview page.
#define D_WIKI_LAYOUT_OVERVIEW       "overview"

// D_WIKI_LAYOUT_CLASS
//   constant: layout key for class/struct pages.
#define D_WIKI_LAYOUT_CLASS          "class"

// D_WIKI_LAYOUT_NAMESPACE
//   constant: layout key for namespace pages.
#define D_WIKI_LAYOUT_NAMESPACE      "namespace"

// D_WIKI_LAYOUT_ENUM
//   constant: layout key for enum pages.
#define D_WIKI_LAYOUT_ENUM           "enum"

// D_WIKI_LAYOUT_FUNCTION_INDEX
//   constant: layout key for the function index page.
#define D_WIKI_LAYOUT_FUNCTION_INDEX "function_index"

// D_WIKI_LAYOUT_MEMBER_ROW
//   constant: layout key for a single member table row.
#define D_WIKI_LAYOUT_MEMBER_ROW     "member_row"


///////////////////////////////////////////////////////////////////////////////
///             VII.  WIKI TEMPLATE CLASS                                   ///
///////////////////////////////////////////////////////////////////////////////

// tmpl_wiki_template
//   class: generates MediaWiki documentation pages from a
// code_parse_result. Inherits from tmpl_template via CRTP;
// transform_impl() maps code_parse_result -> wiki_output.
//
//   Default layouts are built-in as MediaWiki markup strings
// rendered through tmpl_text_template. Each page kind has a
// named layout that can be overridden via set_layout().
//
// usage:
//   cpp_code_template parser(cfg);
//   auto parse = parser.parse_file("myclass.hpp");
//
//   tmpl_wiki_template wiki;
//   auto output = wiki.transform(parse);
//
//   for (const auto& page : output.pages)
//   {
//       upload_to_wiki(page.title, page.content);
//   }
//
// layout override:
//   tmpl_text_template my_class_layout("{{", "}}");
//   my_class_layout.set_format(
//       "= {{name}} =\n{{description}}\n...");
//   wiki.set_layout("class", my_class_layout);
class tmpl_wiki_template
    : public tmpl_template<tmpl_wiki_template,
                           code_parse_result,
                           wiki_output>
{
public:
    using input_type  = code_parse_result;
    using output_type = wiki_output;

    // ---- construction ----

    tmpl_wiki_template()
        : m_config()
        , m_layouts()
    {
    };

    explicit tmpl_wiki_template(wiki_config _config)
        : m_config(std::move(_config))
        , m_layouts()
    {
    };

    // ---- configuration ----

    // config
    //   method: returns a mutable reference to the wiki
    // generation configuration.
    wiki_config& config()
    {
        return m_config;
    };

    const wiki_config& config() const
    {
        return m_config;
    };

    // set_config
    //   method: replaces the wiki configuration.
    void set_config(wiki_config _config)
    {
        m_config = std::move(_config);

        return;
    };


    // =========================================================
    // LAYOUT OVERRIDE POINTS
    // =========================================================

    // set_layout
    //   method: registers a custom text_template layout for
    // a given page kind. The layout template must have its
    // format string set via set_format() before registration.
    // The template is copied; the original need not outlive
    // this call.
    //
    // layout keys: D_WIKI_LAYOUT_OVERVIEW,
    // D_WIKI_LAYOUT_CLASS, D_WIKI_LAYOUT_NAMESPACE,
    // D_WIKI_LAYOUT_ENUM, D_WIKI_LAYOUT_FUNCTION_INDEX,
    // D_WIKI_LAYOUT_MEMBER_ROW
    void set_layout(const std::string& _key,
                    const tmpl_text_template& _layout)
    {
        m_layouts[_key] = _layout;

        return;
    };

    // has_layout
    //   method: returns true if a custom layout is registered
    // for the given key.
    bool has_layout(const std::string& _key) const
    {
        return m_layouts.count(_key) > 0;
    };

    // clear_layout
    //   method: removes a custom layout, reverting to the
    // default for that page kind.
    void clear_layout(const std::string& _key)
    {
        m_layouts.erase(_key);

        return;
    };

    // clear_all_layouts
    //   method: removes all custom layouts.
    void clear_all_layouts()
    {
        m_layouts.clear();

        return;
    };


    // =========================================================
    // TRANSFORM
    // =========================================================

    // transform_impl
    //   method: CRTP implementation. Generates wiki pages
    // from the parse result according to the configuration.
    wiki_output transform_impl(
        const code_parse_result& _parse)
    {
        wiki_output output;

        output.source_file = _parse.source.path;

        if (!_parse.success)
        {
            output.success = false;

            return output;
        }

        // collect symbols by kind for page generation
        std::vector<const code_symbol*> classes;
        std::vector<const code_symbol*> namespaces;
        std::vector<const code_symbol*> enums;
        std::vector<const code_symbol*> functions;

        collect_symbols(
            _parse.symbols,
            classes, namespaces, enums, functions);

        // generate pages
        if (m_config.generate_overview)
        {
            output.pages.push_back(
                generate_overview(
                    _parse, classes, namespaces,
                    enums, functions));
        }

        if (m_config.generate_class_pages)
        {
            for (const auto* sym : classes)
            {
                output.pages.push_back(
                    generate_class_page(*sym));
            }
        }

        if (m_config.generate_namespace_pages)
        {
            for (const auto* sym : namespaces)
            {
                output.pages.push_back(
                    generate_namespace_page(*sym));
            }
        }

        if (m_config.generate_enum_pages)
        {
            for (const auto* sym : enums)
            {
                output.pages.push_back(
                    generate_enum_page(*sym));
            }
        }

        if (m_config.generate_function_index)
        {
            output.pages.push_back(
                generate_function_index(functions));
        }

        output.success = true;

        return output;
    };

private:

    // =========================================================
    // SYMBOL COLLECTION
    // =========================================================

    // collect_symbols
    //   method: partitions top-level symbols into buckets
    // by kind, recursively descending into namespaces.
    void collect_symbols(
        const std::vector<code_symbol>& _syms,
        std::vector<const code_symbol*>& _classes,
        std::vector<const code_symbol*>& _namespaces,
        std::vector<const code_symbol*>& _enums,
        std::vector<const code_symbol*>& _functions)
    {
        for (const auto& sym : _syms)
        {
            switch (sym.kind)
            {
                case code_symbol_kind::class_decl:
                case code_symbol_kind::struct_decl:
                {
                    _classes.push_back(&sym);
                    break;
                }

                case code_symbol_kind::namespace_decl:
                {
                    _namespaces.push_back(&sym);

                    // recurse into namespace children
                    collect_symbols(
                        sym.children,
                        _classes, _namespaces,
                        _enums, _functions);
                    break;
                }

                case code_symbol_kind::enum_decl:
                {
                    _enums.push_back(&sym);
                    break;
                }

                case code_symbol_kind::function_decl:
                {
                    _functions.push_back(&sym);
                    break;
                }

                default:
                {
                    break;
                }
            }
        }

        return;
    };


    // =========================================================
    // LAYOUT RENDERING
    // =========================================================

    // render_layout
    //   method: renders a named layout with the given
    // bindings. If a custom layout is registered, uses it;
    // otherwise uses _default_content directly.
    std::string render_layout(
        const std::string& _key,
        const std::unordered_map<std::string,
            std::string>& _bindings,
        const std::string& _default_content)
    {
        auto it = m_layouts.find(_key);

        if (it == m_layouts.end())
        {
            return _default_content;
        }

        // use custom layout
        tmpl_text_template layout = it->second;

        for (const auto& kv : _bindings)
        {
            layout.bind_string(kv.first, kv.second);
        }

        return layout.render_or(
            layout.format(), _default_content);
    };


    // =========================================================
    // PAGE GENERATION: MODULE OVERVIEW
    // =========================================================

    // generate_overview
    //   method: creates the module overview page.
    wiki_page generate_overview(
        const code_parse_result& _parse,
        const std::vector<const code_symbol*>& _cls,
        const std::vector<const code_symbol*>& _ns,
        const std::vector<const code_symbol*>& _enums,
        const std::vector<const code_symbol*>& _fns)
    {
        std::string content;

        // title
        std::string base_name = _parse.source.path;
        std::size_t slash =
            base_name.find_last_of("/\\");

        if (slash != std::string::npos)
        {
            base_name =
                base_name.substr(slash + 1);
        }

        content += wiki_markup::heading(
            "Module: " + base_name, 1);
        content += "\n";

        // source info
        content += wiki_markup::bold("Source file:")
            + " "
            + wiki_markup::code_inline(
                  _parse.source.path) + "\n\n";

        // dependencies
        if ( (m_config.show_dependencies) &&
             (!_parse.dependencies.empty()) )
        {
            content += wiki_markup::heading(
                "Dependencies");

            for (const auto& dep :
                     _parse.dependencies)
            {
                if (dep.kind ==
                    code_dependency_kind::include)
                {
                    content += wiki_markup::bullet(
                        wiki_markup::code_inline(
                            dep.target));
                }
            }

            content += "\n";
        }

        // classes summary
        if (!_cls.empty())
        {
            content += wiki_markup::heading(
                "Classes");

            content += wiki_markup::table_start();
            content += wiki_markup::table_header(
                {"Name", "Kind", "Description"});

            for (const auto* sym : _cls)
            {
                std::string page_title =
                    make_title(sym->name);

                content += wiki_markup::table_row({
                    wiki_markup::link(
                        page_title, sym->name),
                    wiki_markup::symbol_kind_string(
                        sym->kind),
                    sym->comment.text
                });
            }

            content += wiki_markup::table_end();
            content += "\n";
        }

        // enums summary
        if (!_enums.empty())
        {
            content += wiki_markup::heading(
                "Enumerations");

            for (const auto* sym : _enums)
            {
                std::string page_title =
                    make_title(sym->name);

                content += wiki_markup::bullet(
                    wiki_markup::link(
                        page_title, sym->name)
                    + " &mdash; "
                    + sym->comment.text);
            }

            content += "\n";
        }

        // functions summary
        if (!_fns.empty())
        {
            content += wiki_markup::heading(
                "Functions");

            for (const auto* sym : _fns)
            {
                content += wiki_markup::bullet(
                    wiki_markup::code_inline(
                        sym->signature)
                    + " &mdash; "
                    + sym->comment.text);
            }

            content += "\n";
        }

        // categories
        if (!m_config.default_category.empty())
        {
            content += wiki_markup::category(
                m_config.default_category);
        }

        content += wiki_markup::category("Modules");

        // bindings for layout override
        std::unordered_map<std::string, std::string>
            bindings;

        bindings["module_name"]  = base_name;
        bindings["source_path"]  = _parse.source.path;
        bindings["content"]      = content;

        // assemble page
        wiki_page page;

        page.title   = make_title(base_name);
        page.kind    = wiki_page_kind::module_overview;
        page.content = render_layout(
            D_WIKI_LAYOUT_OVERVIEW,
            bindings, content);

        page.categories.push_back("Modules");

        if (!m_config.default_category.empty())
        {
            page.categories.push_back(
                m_config.default_category);
        }

        return page;
    };


    // =========================================================
    // PAGE GENERATION: CLASS PAGE
    // =========================================================

    // generate_class_page
    //   method: creates a dedicated page for a class or
    // struct.
    wiki_page generate_class_page(
        const code_symbol& _sym)
    {
        std::string content;

        // title
        std::string kind_str =
            wiki_markup::symbol_kind_string(_sym.kind);

        content += wiki_markup::heading(
            kind_str + ": " + _sym.name, 1);
        content += "\n";

        // description
        if (!_sym.comment.text.empty())
        {
            content += _sym.comment.text + "\n\n";
        }

        // signature
        if (!_sym.signature.empty())
        {
            content += wiki_markup::heading(
                "Declaration");
            content += wiki_markup::code_block(
                _sym.signature);
            content += "\n";
        }

        // inheritance
        if ( (m_config.show_inheritance) &&
             (!_sym.bases.empty()) )
        {
            content += wiki_markup::heading(
                "Inheritance");

            for (const auto& base : _sym.bases)
            {
                content += wiki_markup::bullet(
                    wiki_markup::code_inline(base));
            }

            content += "\n";
        }

        // members
        if (!_sym.children.empty())
        {
            content += generate_member_sections(
                _sym.children);
        }

        // source location
        if (m_config.show_source_location)
        {
            content +=
                wiki_markup::heading("Source");
            content +=
                wiki_markup::code_inline(
                    _sym.location.start.file
                    + ":" + std::to_string(
                        _sym.location.start.line))
                + "\n\n";
        }

        // categories
        if (!m_config.default_category.empty())
        {
            content += wiki_markup::category(
                m_config.default_category);
        }

        content += wiki_markup::category("Classes");

        // bindings for layout override
        std::unordered_map<std::string, std::string>
            bindings;

        bindings["name"]        = _sym.name;
        bindings["kind"]        = kind_str;
        bindings["qualified"]   = _sym.qualified_name;
        bindings["signature"]   = _sym.signature;
        bindings["description"] = _sym.comment.text;
        bindings["content"]     = content;

        // assemble page
        wiki_page page;

        page.title         = make_title(_sym.name);
        page.kind          = wiki_page_kind::class_page;
        page.source_symbol = _sym.qualified_name;
        page.content       = render_layout(
            D_WIKI_LAYOUT_CLASS,
            bindings, content);

        page.categories.push_back("Classes");

        return page;
    };


    // =========================================================
    // PAGE GENERATION: NAMESPACE PAGE
    // =========================================================

    // generate_namespace_page
    //   method: creates a dedicated page for a namespace.
    wiki_page generate_namespace_page(
        const code_symbol& _sym)
    {
        std::string content;

        content += wiki_markup::heading(
            "Namespace: " + _sym.name, 1);
        content += "\n";

        if (!_sym.comment.text.empty())
        {
            content += _sym.comment.text + "\n\n";
        }

        // list children by kind
        if (!_sym.children.empty())
        {
            content += generate_member_sections(
                _sym.children);
        }

        if (!m_config.default_category.empty())
        {
            content += wiki_markup::category(
                m_config.default_category);
        }

        content +=
            wiki_markup::category("Namespaces");

        // bindings
        std::unordered_map<std::string, std::string>
            bindings;

        bindings["name"]        = _sym.name;
        bindings["qualified"]   = _sym.qualified_name;
        bindings["description"] = _sym.comment.text;
        bindings["content"]     = content;

        // assemble
        wiki_page page;

        page.title         = make_title(_sym.name);
        page.kind          =
            wiki_page_kind::namespace_page;
        page.source_symbol = _sym.qualified_name;
        page.content       = render_layout(
            D_WIKI_LAYOUT_NAMESPACE,
            bindings, content);

        page.categories.push_back("Namespaces");

        return page;
    };


    // =========================================================
    // PAGE GENERATION: ENUM PAGE
    // =========================================================

    // generate_enum_page
    //   method: creates a dedicated page for an enum.
    wiki_page generate_enum_page(
        const code_symbol& _sym)
    {
        std::string content;

        content += wiki_markup::heading(
            "Enum: " + _sym.name, 1);
        content += "\n";

        if (!_sym.comment.text.empty())
        {
            content += _sym.comment.text + "\n\n";
        }

        if (!_sym.signature.empty())
        {
            content += wiki_markup::heading(
                "Declaration");
            content += wiki_markup::code_block(
                _sym.signature);
            content += "\n";
        }

        // enumerators
        if (!_sym.children.empty())
        {
            content += wiki_markup::heading(
                "Values");

            content += wiki_markup::table_start();
            content += wiki_markup::table_header(
                {"Name", "Description"});

            for (const auto& child : _sym.children)
            {
                content += wiki_markup::table_row({
                    wiki_markup::code_inline(
                        child.name),
                    child.comment.text
                });
            }

            content += wiki_markup::table_end();
            content += "\n";
        }

        if (!m_config.default_category.empty())
        {
            content += wiki_markup::category(
                m_config.default_category);
        }

        content +=
            wiki_markup::category("Enumerations");

        // bindings
        std::unordered_map<std::string, std::string>
            bindings;

        bindings["name"]        = _sym.name;
        bindings["qualified"]   = _sym.qualified_name;
        bindings["description"] = _sym.comment.text;
        bindings["content"]     = content;

        // assemble
        wiki_page page;

        page.title         = make_title(_sym.name);
        page.kind          = wiki_page_kind::enum_page;
        page.source_symbol = _sym.qualified_name;
        page.content       = render_layout(
            D_WIKI_LAYOUT_ENUM,
            bindings, content);

        page.categories.push_back("Enumerations");

        return page;
    };


    // =========================================================
    // PAGE GENERATION: FUNCTION INDEX
    // =========================================================

    // generate_function_index
    //   method: creates an alphabetical index of all
    // functions.
    wiki_page generate_function_index(
        const std::vector<const code_symbol*>& _fns)
    {
        std::string content;

        content += wiki_markup::heading(
            "Function Index", 1);
        content += "\n";

        if (_fns.empty())
        {
            content += wiki_markup::italic(
                "No functions found.") + "\n";
        }
        else
        {
            content += wiki_markup::table_start();
            content += wiki_markup::table_header(
                {"Function", "Return Type",
                 "Description"});

            for (const auto* sym : _fns)
            {
                content += wiki_markup::table_row({
                    wiki_markup::code_inline(
                        sym->name),
                    wiki_markup::code_inline(
                        sym->return_type.empty()
                            ? "void"
                            : sym->return_type),
                    sym->comment.text
                });
            }

            content += wiki_markup::table_end();
        }

        content += "\n";

        if (!m_config.default_category.empty())
        {
            content += wiki_markup::category(
                m_config.default_category);
        }

        content +=
            wiki_markup::category("Functions");

        // bindings
        std::unordered_map<std::string, std::string>
            bindings;

        bindings["content"] = content;

        // assemble
        wiki_page page;

        page.title   = make_title("Function Index");
        page.kind    =
            wiki_page_kind::function_index;
        page.content = render_layout(
            D_WIKI_LAYOUT_FUNCTION_INDEX,
            bindings, content);

        page.categories.push_back("Functions");

        return page;
    };


    // =========================================================
    // MEMBER SECTIONS
    // =========================================================

    // generate_member_sections
    //   method: generates member tables grouped by access
    // specifier and symbol kind.
    std::string generate_member_sections(
        const std::vector<code_symbol>& _members)
    {
        std::string content;

        // group: types (typedefs, aliases, nested)
        std::string types = generate_member_table(
            _members, "Types",
            [](const code_symbol& _s)
            {
                return ( (_s.kind ==
                    code_symbol_kind::typedef_decl) ||
                    (_s.kind ==
                    code_symbol_kind::type_alias) ||
                    (_s.kind ==
                    code_symbol_kind::class_decl) ||
                    (_s.kind ==
                    code_symbol_kind::struct_decl) ||
                    (_s.kind ==
                    code_symbol_kind::enum_decl) );
            });

        // group: methods
        std::string methods = generate_member_table(
            _members, "Methods",
            [](const code_symbol& _s)
            {
                return ( (_s.kind ==
                    code_symbol_kind::method_decl) ||
                    (_s.kind ==
                    code_symbol_kind::constructor) ||
                    (_s.kind ==
                    code_symbol_kind::destructor) ||
                    (_s.kind ==
                    code_symbol_kind::operator_decl) );
            });

        // group: data members
        std::string fields = generate_member_table(
            _members, "Data Members",
            [](const code_symbol& _s)
            {
                return ( (_s.kind ==
                    code_symbol_kind::field_decl) ||
                    (_s.kind ==
                    code_symbol_kind::variable_decl) );
            });

        content += types;
        content += methods;
        content += fields;

        return content;
    };

    // generate_member_table
    //   method: generates a table of members matching a
    // filter predicate.
    std::string generate_member_table(
        const std::vector<code_symbol>& _members,
        const std::string& _heading,
        std::function<bool(const code_symbol&)> _filter)
    {
        // collect matching members
        std::vector<const code_symbol*> matched;

        for (const auto& member : _members)
        {
            if (_filter(member))
            {
                matched.push_back(&member);
            }
        }

        if (matched.empty())
        {
            return std::string();
        }

        std::string content;

        content += wiki_markup::heading(_heading, 3);

        content += wiki_markup::table_start();

        std::vector<std::string> headers =
            {"Name", "Signature", "Description"};

        if (m_config.show_access)
        {
            headers.insert(
                headers.begin(), "Access");
        }

        content += wiki_markup::table_header(headers);

        for (const auto* sym : matched)
        {
            std::vector<std::string> cells;

            if (m_config.show_access)
            {
                cells.push_back(
                    wiki_markup::access_string(
                        sym->access));
            }

            cells.push_back(
                wiki_markup::code_inline(sym->name));
            cells.push_back(
                wiki_markup::code_inline(
                    sym->signature));
            cells.push_back(sym->comment.text);

            content += wiki_markup::table_row(cells);
        }

        content += wiki_markup::table_end();
        content += "\n";

        return content;
    };


    // =========================================================
    // TITLE HELPERS
    // =========================================================

    // make_title
    //   method: constructs a wiki page title from a symbol
    // name, applying the configured prefix.
    std::string make_title(
        const std::string& _name) const
    {
        if (m_config.title_prefix.empty())
        {
            return _name;
        }

        return m_config.title_prefix + _name;
    };


    // ---- members ----

    wiki_config m_config;

    std::unordered_map<std::string,
                       tmpl_text_template>
        m_layouts;
};


NS_END  // templatinum
NS_END  // djinterp


#endif  // TEMPLATINUM_WIKI_TEMPLATE_
